services:
  app:
    image: ghcr.io/ashshakya/localmachine:${TAG}
    container_name: localmachine

    restart: unless-stopped

    env_file:
      - /home/deploy/.env

    ports:
      - "8000:8000"